trigger:
  branches:
    include:
      - staging
  excludeMessage:
    startsWith:
      - 'Bump version'
  tags:
    exclude:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self
    persistCredentials: true
    clean: true
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm install -g typescript
      echo "Installing env-cmd..."
      npm install -g env-cmd
    displayName: 'npm install'
  - script: |
      echo "Building the React app..."
      npm run build
    displayName: 'Building the app'

  - task: FtpUpload@2
    inputs:
      credentialsOption: 'inputs'
      serverUrl: $(FTP_SERVER)
      username: $(FTP_USERNAME)
      password: $(FTP_PASSWORD)
      rootDirectory: './build'
      filePatterns: '**'
      remoteDirectory: $(FTP_FOLDER)
      clean: false
      cleanContents: true
      preservePaths: true
      trustSSL: true
    displayName: 'Uploading to the FTP'
