trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  majorVersion: 1
  minorVersion: 0
  patchVersion: $[counter(format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0)]


steps:
  - script: |
      echo Installing Node.js...
      curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      sudo apt-get install -y nodejs
    displayName: 'Install Node.js'

  - script: |
      echo Installing dependencies...
      npm install
      npm install -g typescript
    displayName: 'Install Dependencies'

  - script: |
      echo Increasing app version...
      export GH_TOKEN=$(GITHUB_TOKEN)
      echo https://$GH_TOKEN@github.com:Huskerfromthehill/builderrocket-ui.git
      npm version $(majorVersion).$(minorVersion).$(patchVersion)
      git config --global user.email "dev.doublemwebsolutions@gmail.com"
      git config --global user.name "Azure Pipline"
      git remote set-url origin https://$GH_TOKEN@github.com:Huskerfromthehill/builderrocket-ui.git
      git tag -a v$(majorVersion).$(minorVersion).$(patchVersion) -m "Version $(majorVersion).$(minorVersion).$(patchVersion)"
      git push origin v$(majorVersion).$(minorVersion).$(patchVersion)
    displayName: 'npm install, increase version & push tag'
    
  - script: |
      echo Building the React app...
      npm run build
    displayName: 'Build'

