trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  majorVersion: 1
  minorVersion: 0
  patchVersion: $[counter(format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0)]

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g typescript
  displayName: 'npm install, increase version & push tag'
  
- task: PowerShell@2
  displayName: 'Bump the version'
  inputs:
      targetType: 'inline'

- script: |
        $BranchName = "$(Build.SourceBranch)" -replace "refs/heads/"
        git checkout $BranchName
        git config --global user.email "dev.doublemwebsolutions@gmail.com"
        git config --global user.name "Azure Pipline"
        npm version $(majorVersion).$(minorVersion).$(patchVersion)
        git tag -a v$(majorVersion).$(minorVersion).$(patchVersion) -m "Version $(majorVersion).$(minorVersion).$(patchVersion)"
        git push origin v$(majorVersion).$(minorVersion).$(patchVersion)