trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  majorVersion: 1
  minorVersion: 0
  patchVersion: $[counter(format('{0}.{1}', variables['majorVersion'], variables['minorVersion']), 0)]

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g typescript
  displayName: 'npm install'
  
- task: PowerShell@2
  displayName: 'increase version & push tag'
  inputs:
      targetType: 'inline'

- script: |
        $BranchName = "$(Build.SourceBranch)"
        git config --global user.email "dev.doublemwebsolutions@gmail.com"
        git config --global user.name "Azure Pipeline"
        echo "Increase version from: $(majorVersion).$(minorVersion).$(patchVersion)"
        npm version $(majorVersion).$(minorVersion).$(patchVersion)
        nVersion="$(majorVersion).$(minorVersion).$(patchVersion)"
        echo "To: $nVersion"
        git checkout $BranchName
        echo "New Version: v$nVersion"
        git tag -a v$nVersion -m "Version $nVersion"
        git add . 
        git commit -m "Bump version to $nVersion"
        git push origin v$nVersion
