// auth 
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const SET_USER = 'SET_USER';

//customer Project
export const SET_CUSTOMER_PROJECT = 'SET_CUSTOMER_PROJECT';

// projects
export const GET_PROJECT = 'GET_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const RESET_PROJECT = 'RESET_PROJECT';
export const ADD_PROJECT_ROOMS = 'ADD_PROJECT_ROOMS';
export const DELETE_PROJECT_ROOMS = 'DELETE_PROJECT_ROOMS';
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const SET_REFRESH_THUMBNAIL = 'SET_REFRESH_THUMBNAIL';
export const SET_SELECTED_PROJECT_TAB = 'SET_SELECTED_PROJECT_TAB';

export const GET_LOGOS = 'GET_LOGOS';

export const GET_REPORT = 'GET_REPORT';
export const GET_CATEGORIZED_REPORT = 'GET_CATEGORIZED_REPORT';
export const GET_ROOM_REPORT = 'GET_ROOM_REPORT';
export const GET_VENDOR_REPORT = 'GET_VENDOR_REPORT';


// user
export const GET_USER_PROFILE = 'GET_USER_PROFILE';

// subdivision
export const GET_SUBDIVISIONS = 'GET_SUBDIVISIONS';
export const ADD_SUBDIVISION = 'ADD_SUBDIVISION';

// utility
export const GET_UTILITIES = 'GET_UTILITIES';
export const CREATE_UTILITY = 'CREATE_UTILITY';
export const GET_UTILITY_TYPES = 'GET_UTILITY_TYPES';
export const SET_SELECTED_UTILITY = 'SET_SELECTED_UTILITY';

// documents 
export const GET_DOCUMENT_TYPES = 'GET_DOCUMENT_TYPES';

// contractor
export const GET_CONTRACTORS = 'GET_CONTRACTORS';
export const CREATE_CONTRACTOR = 'CREATE_CONTRACTOR';
export const GET_CONTRACTOR_TYPES = 'GET_CONTRACTOR_TYPES';
export const SET_SELECTED_CONTRACTOR = 'SET_SELECTED_CONTRACTOR';

// room 
export const GET_ROOM = 'GET_ROOM';
export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOM_TYPES = 'GET_ROOM_TYPES';
export const SET_SELECTED_ROOM = 'SET_SELECTED_ROOM';

// product 
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_REPLACE_PRODUCT = 'SET_REPLACE_PRODUCT';
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const SET_PRODUCT_DETAIL = 'SET_PRODUCT_DETAIL';
export const GET_CHILD_CATEGORIES = 'GET_CHILD_CATEGORIES';
export const SET_SELECTED_PRODUCT_TAB = 'SET_SELECTED_PRODUCT_TAB';
export const SET_SELECTED_CATEGORY_ID = 'SET_SELECTED_CATEGORY_ID';

//report
export const SET_REPORTS_FILTR = 'SET_REPORTS_FILTR';
export const GET_REPORTS_FILTER = 'GET_REPORTS_FILTER';


